package jogo;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

//classe que representa a janela de configuração do jogo e salva em arquivo
public class Config extends javax.swing.JFrame {

    int[] valores;
    String[] tipos;
    int i=0;
    /**
     * Creates new form Config
     */
    public Config() {
        valores = new int[12];
        tipos = new String[12];
        Image icon = (new ImageIcon(getClass().getResource("/Frutas/Abacaxi.png"))).getImage();
        setIconImage(icon);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dimensao = new javax.swing.ButtonGroup();
        Grama = new javax.swing.ButtonGroup();
        Pedras = new javax.swing.ButtonGroup();
        Arvores = new javax.swing.ButtonGroup();
        FrutasOuro = new javax.swing.ButtonGroup();
        FrutasNaoOuro = new javax.swing.ButtonGroup();
        FrutasBixadas = new javax.swing.ButtonGroup();
        Mochilaa = new javax.swing.ButtonGroup();
        Melanciaa = new javax.swing.ButtonGroup();
        Morangoo = new javax.swing.ButtonGroup();
        Laranjaa = new javax.swing.ButtonGroup();
        Abacatee = new javax.swing.ButtonGroup();
        TipoArvore = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dim3 = new javax.swing.JRadioButton();
        dim4 = new javax.swing.JRadioButton();
        dim5 = new javax.swing.JRadioButton();
        fo3 = new javax.swing.JRadioButton();
        fo4 = new javax.swing.JRadioButton();
        fo5 = new javax.swing.JRadioButton();
        fno20 = new javax.swing.JRadioButton();
        fno50 = new javax.swing.JRadioButton();
        fno70 = new javax.swing.JRadioButton();
        fb30 = new javax.swing.JRadioButton();
        fb15 = new javax.swing.JRadioButton();
        fb5 = new javax.swing.JRadioButton();
        mochila3 = new javax.swing.JRadioButton();
        mochila4 = new javax.swing.JRadioButton();
        mochila5 = new javax.swing.JRadioButton();
        pe20 = new javax.swing.JRadioButton();
        pe15 = new javax.swing.JRadioButton();
        pe25 = new javax.swing.JRadioButton();
        arv25 = new javax.swing.JRadioButton();
        arv20 = new javax.swing.JRadioButton();
        arv15 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        me5 = new javax.swing.JRadioButton();
        me15 = new javax.swing.JRadioButton();
        me30 = new javax.swing.JRadioButton();
        la5 = new javax.swing.JRadioButton();
        la15 = new javax.swing.JRadioButton();
        la30 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        ab5 = new javax.swing.JRadioButton();
        ab30 = new javax.swing.JRadioButton();
        ab15 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        melancia = new javax.swing.JRadioButton();
        laranja = new javax.swing.JRadioButton();
        abacate = new javax.swing.JRadioButton();
        abacaxi = new javax.swing.JRadioButton();
        morango = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Dimensão");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Pedras");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Árvores");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Abacaxi");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Frutas-não-ouro");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Frutas bixadas");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Capacidade da Mochila");

        Dimensao.add(dim3);
        dim3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dim3.setText("3x3(default)");
        dim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dim3ActionPerformed(evt);
            }
        });

        Dimensao.add(dim4);
        dim4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dim4.setText("4x4");
        dim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dim4ActionPerformed(evt);
            }
        });

        Dimensao.add(dim5);
        dim5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dim5.setText("5x5");
        dim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dim5ActionPerformed(evt);
            }
        });

        FrutasOuro.add(fo3);
        fo3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fo3.setText("3(default)");
        fo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fo3ActionPerformed(evt);
            }
        });

        FrutasOuro.add(fo4);
        fo4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fo4.setText("4");
        fo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fo4ActionPerformed(evt);
            }
        });

        FrutasOuro.add(fo5);
        fo5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fo5.setText("5");
        fo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fo5ActionPerformed(evt);
            }
        });

        FrutasNaoOuro.add(fno20);
        fno20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fno20.setText("20%(default)");
        fno20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fno20ActionPerformed(evt);
            }
        });

        FrutasNaoOuro.add(fno50);
        fno50.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fno50.setText("50%");
        fno50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fno50ActionPerformed(evt);
            }
        });

        FrutasNaoOuro.add(fno70);
        fno70.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fno70.setText("70%");
        fno70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fno70ActionPerformed(evt);
            }
        });

        FrutasBixadas.add(fb30);
        fb30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fb30.setText("15%");
        fb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb30ActionPerformed(evt);
            }
        });

        FrutasBixadas.add(fb15);
        fb15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fb15.setText("30%(default)");
        fb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb15ActionPerformed(evt);
            }
        });

        FrutasBixadas.add(fb5);
        fb5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fb5.setText("45%");
        fb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fb5ActionPerformed(evt);
            }
        });

        Mochilaa.add(mochila3);
        mochila3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mochila3.setText("3(default)");
        mochila3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochila3ActionPerformed(evt);
            }
        });

        Mochilaa.add(mochila4);
        mochila4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mochila4.setText("4");
        mochila4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochila4ActionPerformed(evt);
            }
        });

        Mochilaa.add(mochila5);
        mochila5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mochila5.setText("5");
        mochila5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochila5ActionPerformed(evt);
            }
        });

        Pedras.add(pe20);
        pe20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pe20.setText("20%");
        pe20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pe20ActionPerformed(evt);
            }
        });

        Pedras.add(pe15);
        pe15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pe15.setText("15%");
        pe15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pe15ActionPerformed(evt);
            }
        });

        Pedras.add(pe25);
        pe25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pe25.setText("25%(default)");
        pe25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pe25ActionPerformed(evt);
            }
        });

        Arvores.add(arv25);
        arv25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        arv25.setText("25%(default)");
        arv25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arv25ActionPerformed(evt);
            }
        });

        Arvores.add(arv20);
        arv20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        arv20.setText("20%");
        arv20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arv20ActionPerformed(evt);
            }
        });

        Arvores.add(arv15);
        arv15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        arv15.setText("15%");
        arv15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arv15ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel9.setText("Configurações");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Melancia");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Laranja");

        Melanciaa.add(me5);
        me5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        me5.setText("5%(default)");
        me5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                me5ActionPerformed(evt);
            }
        });

        Melanciaa.add(me15);
        me15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        me15.setText("15%");
        me15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                me15ActionPerformed(evt);
            }
        });

        Melanciaa.add(me30);
        me30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        me30.setText("30%");
        me30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                me30ActionPerformed(evt);
            }
        });

        Laranjaa.add(la5);
        la5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        la5.setText("5%");
        la5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la5ActionPerformed(evt);
            }
        });

        Laranjaa.add(la15);
        la15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        la15.setText("15%(default)");
        la15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la15ActionPerformed(evt);
            }
        });

        Laranjaa.add(la30);
        la30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        la30.setText("30%");
        la30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la30ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Abacate");

        Abacatee.add(ab5);
        ab5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ab5.setText("5%(default)");
        ab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab5ActionPerformed(evt);
            }
        });

        Abacatee.add(ab30);
        ab30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ab30.setText("30%");
        ab30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab30ActionPerformed(evt);
            }
        });

        Abacatee.add(ab15);
        ab15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ab15.setText("15%");
        ab15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ab15ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException ex) {
                    Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de Árvore");

        TipoArvore.add(melancia);
        melancia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        melancia.setText("Melancia");
        melancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melanciaActionPerformed(evt);
            }
        });

        TipoArvore.add(laranja);
        laranja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        laranja.setText("Laranja");
        laranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laranjaActionPerformed(evt);
            }
        });

        TipoArvore.add(abacate);
        abacate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        abacate.setText("Abacate");
        abacate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abacateActionPerformed(evt);
            }
        });

        TipoArvore.add(abacaxi);
        abacaxi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        abacaxi.setText("Abacaxi");
        abacaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abacaxiActionPerformed(evt);
            }
        });

        TipoArvore.add(morango);
        morango.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        morango.setText("Morango");
        morango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morangoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mochila5)
                        .addComponent(mochila3)
                        .addComponent(mochila4)
                        .addComponent(jLabel8))
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fo3)
                                .addComponent(fo4)
                                .addComponent(fo5)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fno50)
                                .addComponent(fno70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(fno20)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pe25)
                                        .addComponent(pe20)
                                        .addComponent(pe15)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabel3)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fb15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fb5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fb30, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(arv20)
                                            .addComponent(arv25)
                                            .addComponent(arv15))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(30, 30, 30)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addGap(40, 40, 40))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dim3)
                                        .addComponent(dim4)
                                        .addComponent(dim5)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel1)))
                                    .addGap(285, 285, 285))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel10))
                                        .addComponent(me5)
                                        .addComponent(me30)
                                        .addComponent(me15))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(la30, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(la15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(la5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(jLabel12)))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ab5)
                                        .addComponent(ab15)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel13))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(ab30)
                                            .addGap(34, 34, 34)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(abacate)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(melancia)
                                        .addComponent(laranja))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(morango)
                                        .addComponent(abacaxi))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pe25)
                            .addComponent(dim3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pe20)
                            .addComponent(dim4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dim5)
                            .addComponent(pe15)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(arv25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(arv20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(arv15))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(melancia)
                                .addComponent(abacaxi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(laranja)
                                .addComponent(morango))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(abacate))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fo3)
                            .addComponent(fb30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fo5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fb15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fb5))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fno20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fno50)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fno70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mochila3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mochila4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mochila5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(me5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(me15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(me30))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(la5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(la15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(la30)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ab5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ab15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ab30)
                            .addComponent(jButton1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dim3ActionPerformed
        // TODO add your handling code here:
        Floresta.setDimensaoFloresta(3);
        tipos[i]="Dimensao da floresta:";
        valores[i]=3;
        i++;
    }//GEN-LAST:event_dim3ActionPerformed

    private void dim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dim4ActionPerformed
        // TODO add your handling code here:
        Floresta.setDimensaoFloresta(4);
        tipos[i]="Dimensao da floresta:";
        valores[i]=4;
        i++;
    }//GEN-LAST:event_dim4ActionPerformed

    private void dim5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dim5ActionPerformed
        // TODO add your handling code here:
        Floresta.setDimensaoFloresta(5);
        tipos[i]="Dimensao da floresta:";
        valores[i]=5;
        i++;
    }//GEN-LAST:event_dim5ActionPerformed

    private void pe25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pe25ActionPerformed
        // TODO add your handling code here:
        Pedra.setQuantidade(25);
        tipos[i]="Porcentagem de pedras:";
        valores[i]=25;
        i++;
    }//GEN-LAST:event_pe25ActionPerformed

    private void pe20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pe20ActionPerformed
        // TODO add your handling code here:
        Pedra.setQuantidade(20);
        tipos[i]="Porcentagem de pedras:";
        valores[i]=20;
        i++;
    }//GEN-LAST:event_pe20ActionPerformed

    private void pe15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pe15ActionPerformed
        // TODO add your handling code here:
        Pedra.setQuantidade(15);
        tipos[i]="Porcentagem de pedras:";
        valores[i]=15;
        i++;
    }//GEN-LAST:event_pe15ActionPerformed

    private void arv25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arv25ActionPerformed
        // TODO add your handling code here:
       Arvore.setQuantidade(25);
       tipos[i]="Porcentagem de árvores:";
       valores[i]=3;
        i++;
    }//GEN-LAST:event_arv25ActionPerformed

    private void arv20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arv20ActionPerformed
        // TODO add your handling code here:
        Arvore.setQuantidade(20);
        tipos[i]="Porcentagem de árvores:";
        valores[i]=20;
        i++;
    }//GEN-LAST:event_arv20ActionPerformed

    private void arv15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arv15ActionPerformed
        // TODO add your handling code here:
        Arvore.setQuantidade(15);
        tipos[i]="Porcentagem de árvores:";
        valores[i]=15;
        i++;
    }//GEN-LAST:event_arv15ActionPerformed

    private void fo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fo3ActionPerformed
        // TODO add your handling code here:
        Abacaxi.setTotalDeOuro(3);
        tipos[i]="Quantidade de frutas ouro:";
        valores[i]=3;
        i++;
    }//GEN-LAST:event_fo3ActionPerformed

    private void fo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fo4ActionPerformed
        // TODO add your handling code here:
        Abacaxi.setTotalDeOuro(4);
        tipos[i]="Quantidade de frutas ouro:";
        valores[i]=4;
        i++;
    }//GEN-LAST:event_fo4ActionPerformed

    private void fo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fo5ActionPerformed
        // TODO add your handling code here:
            Abacaxi.setTotalDeOuro(5);
            tipos[i]="Quantidade de frutas ouro:";
            valores[i]=5;
        i++;
    }//GEN-LAST:event_fo5ActionPerformed

    private void fno20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fno20ActionPerformed
        // TODO add your handling code here:
        Fruta.setTotalDeFrutasNaoOuro(20);
        tipos[i]="Porcentagem de frutas não ouro:";
        valores[i]=20;
        i++;
    }//GEN-LAST:event_fno20ActionPerformed

    private void fno50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fno50ActionPerformed
        // TODO add your handling code here:
        Fruta.setTotalDeFrutasNaoOuro(50);
        tipos[i]="Porcentagem de frutas não ouro:";
        valores[i]=50;
        i++;
    }//GEN-LAST:event_fno50ActionPerformed

    private void fno70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fno70ActionPerformed
        // TODO add your handling code here:
        Fruta.setTotalDeFrutasNaoOuro(70);
        tipos[i]="Porcentagem de frutas não ouro:";
        valores[i]=70;
        i++;
    }//GEN-LAST:event_fno70ActionPerformed

    private void fb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb30ActionPerformed
        // TODO add your handling code here:
        Fruta.setTotalDeFrutasBichadas(15);
        tipos[i]="Porcentagem de frutas bichadas:";
        valores[i]=15;
        i++;
    }//GEN-LAST:event_fb30ActionPerformed

    private void fb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb15ActionPerformed
        // TODO add your handling code here:
        Fruta.setTotalDeFrutasBichadas(30);
        tipos[i]="Porcentagem de frutas bichadas:";
        valores[i]=30;
        i++;
    }//GEN-LAST:event_fb15ActionPerformed

    private void fb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fb5ActionPerformed
        // TODO add your handling code here:
        Fruta.setTotalDeFrutasBichadas(45);
        tipos[i]="Porcentagem de frutas bichadas:";
        valores[i]=45;
        i++;
    }//GEN-LAST:event_fb5ActionPerformed

    private void mochila3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochila3ActionPerformed
        // TODO add your handling code here:
        Mochila.setCapacidade(3);
        tipos[i]="Capacidade da mochila:";
        valores[i]=3;
        i++;
    }//GEN-LAST:event_mochila3ActionPerformed

    private void mochila4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochila4ActionPerformed
        // TODO add your handling code here:
        Mochila.setCapacidade(4);
        tipos[i]="Capacidade da mochila:";
        valores[i]=4;
        i++;
    }//GEN-LAST:event_mochila4ActionPerformed

    private void mochila5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochila5ActionPerformed
        // TODO add your handling code here:
        Mochila.setCapacidade(5);
        tipos[i]="Capacidade da mochila:";
        valores[i]=5;
        i++;
    }//GEN-LAST:event_mochila5ActionPerformed

    private void me5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_me5ActionPerformed
        // TODO add your handling code here:
        Melancia.setTotalDeMelancia(5);
        tipos[i]="Porcentagem de melancia:";
        valores[i]=5;
        i++;
    }//GEN-LAST:event_me5ActionPerformed

    private void me15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_me15ActionPerformed
        // TODO add your handling code here:
        Melancia.setTotalDeMelancia(15);
        tipos[i]="Porcentagem de melancia:";
        valores[i]=15;
        i++;
    }//GEN-LAST:event_me15ActionPerformed

    private void me30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_me30ActionPerformed
        // TODO add your handling code here:
        Melancia.setTotalDeMelancia(30);
        tipos[i]="Porcentagem de melancia:";
        valores[i]=30;
        i++;
    }//GEN-LAST:event_me30ActionPerformed

    private void la5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la5ActionPerformed
        // TODO add your handling code here:
        Laranja.setTotalDeLaranja(5);
        tipos[i]="Porcentagem de laranja:";
        valores[i]=5;
        i++;
    }//GEN-LAST:event_la5ActionPerformed

    private void la15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la15ActionPerformed
        // TODO add your handling code here:
        Laranja.setTotalDeLaranja(15);
        tipos[i]="Porcentagem de laranja:";
        valores[i]=15;
        i++;
    }//GEN-LAST:event_la15ActionPerformed

    private void la30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la30ActionPerformed
        // TODO add your handling code here:
        Laranja.setTotalDeLaranja(30);
        tipos[i]="Porcentagem de laranja:";
        valores[i]=30;
        i++;
    }//GEN-LAST:event_la30ActionPerformed

    private void ab5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab5ActionPerformed
        // TODO add your handling code here:
        Abacate.setTotalDeAbacate(5);
        tipos[i]="Porcentagem de abacate:";
        valores[i]=5;
        i++;
    }//GEN-LAST:event_ab5ActionPerformed

    private void ab15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab15ActionPerformed
        // TODO add your handling code here:
        Abacate.setTotalDeAbacate(15);
        tipos[i]="Porcentagem de abacate:";
        valores[i]=15;
        i++;
    }//GEN-LAST:event_ab15ActionPerformed

    private void ab30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ab30ActionPerformed
        // TODO add your handling code here:
        Abacate.setTotalDeAbacate(30);
        tipos[i]="Porcentagem de abacate:";
        valores[i]=30;
        i++;
    }//GEN-LAST:event_ab30ActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException{ //salvar arquivo
        File file = new  File("configuraçoes.txt");
        BufferedWriter buffer = new BufferedWriter(new FileWriter (file));
        buffer.write("-----Configurações-----");
        buffer.newLine();
         for(int j = 0; j <i; j++){
             buffer.write(tipos[j]);
             buffer.write(String.valueOf(valores[j]));  
             buffer.newLine();
       }
       buffer.close();

        System.out.printf("Configurações gravadas com sucesso em configuraçoes.txt");
        dispose();
    }
    private void melanciaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Arvore.setTipoArvore(2);
        tipos[i]="Tipo das árvores:";
        valores[i]=2;
        i++;
    }                                        

    private void laranjaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Arvore.setTipoArvore(4);
        tipos[i]="Tipo das árvores:";
        valores[i]=4;
        i++;
        
    }                                       

    private void abacateActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Arvore.setTipoArvore(3);
        tipos[i]="Tipo das árvores:";
        valores[i]=3;
        i++;
    }                                       

    private void abacaxiActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Arvore.setTipoArvore(1);
        tipos[i]="Tipo das árvores:";
        valores[i]=1;
        i++;
    }                                       

    private void morangoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        Arvore.setTipoArvore(5);
        tipos[i]="Tipo das árvores:";
        valores[i]=5;
        i++;
    }    
                                 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Config().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Abacatee;
    private javax.swing.ButtonGroup Arvores;
    private javax.swing.ButtonGroup Dimensao;
    private javax.swing.ButtonGroup FrutasBixadas;
    private javax.swing.ButtonGroup FrutasNaoOuro;
    private javax.swing.ButtonGroup FrutasOuro;
    private javax.swing.ButtonGroup Grama;
    private javax.swing.ButtonGroup Laranjaa;
    private javax.swing.ButtonGroup Melanciaa;
    private javax.swing.ButtonGroup Mochilaa;
    private javax.swing.ButtonGroup Morangoo;
    private javax.swing.ButtonGroup Pedras;
    private javax.swing.JRadioButton ab15;
    private javax.swing.JRadioButton ab30;
    private javax.swing.JRadioButton ab5;
    private javax.swing.JRadioButton arv15;
    private javax.swing.JRadioButton arv20;
    private javax.swing.JRadioButton arv25;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton dim3;
    private javax.swing.JRadioButton dim4;
    private javax.swing.JRadioButton dim5;
    private javax.swing.JRadioButton fb15;
    private javax.swing.JRadioButton fb30;
    private javax.swing.JRadioButton fb5;
    private javax.swing.JRadioButton fno20;
    private javax.swing.JRadioButton fno50;
    private javax.swing.JRadioButton fno70;
    private javax.swing.JRadioButton fo3;
    private javax.swing.JRadioButton fo4;
    private javax.swing.JRadioButton fo5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton la15;
    private javax.swing.JRadioButton la30;
    private javax.swing.JRadioButton la5;
    private javax.swing.JRadioButton me15;
    private javax.swing.JRadioButton me30;
    private javax.swing.JRadioButton me5;
    private javax.swing.JRadioButton mochila3;
    private javax.swing.JRadioButton mochila4;
    private javax.swing.JRadioButton mochila5;
    private javax.swing.JRadioButton pe15;
    private javax.swing.JRadioButton pe20;
    private javax.swing.JRadioButton pe25;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton melancia;
    private javax.swing.JRadioButton laranja;
    private javax.swing.JRadioButton abacate;
    private javax.swing.JRadioButton abacaxi;
    private javax.swing.JRadioButton morango;
    private javax.swing.ButtonGroup TipoArvore;
    // End of variables declaration//GEN-END:variables
}
