package jogo;

import java.awt.Color;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

//classe que contém a tela inicial, com botões para chamar as telas secundárias
public class Jogo extends javax.swing.JFrame {
    private static Floresta floresta;
    private static MatrizFrutas frutas;
    private static Avatar avatar1;
    private static Avatar avatar2;
    private static JanelaJogo janela1;
    private static int ultimoAJogar=2;
    private static float totalDeRodadas=0.0f;
    
    /**
     * Creates new form Jougo
     */
    
    
    public Jogo() {
        initComponents();
        Image icon = (new ImageIcon(getClass().getResource("/Frutas/Abacaxi.png"))).getImage();
        setIconImage(icon);
    }
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Play - Caça Frutas");

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.setBackground(Color.green);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 260, 290, 30);

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton2.setText("Configurações");
        jButton2.setBackground(Color.cyan);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 310, 290, 30);

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton3.setText("Créditos");
        jButton3.setBackground(Color.orange);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 360, 290, 30);
        
        jButton4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jButton4.setText("Música");
        jButton4.setBackground(Color.white);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton4ActionPerformed(evt);
                } catch (UnsupportedAudioFileException ex) {
                    Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 10, 120, 29);
        
        jLabel2.setIcon(new ImageIcon(getClass().getResource("/Cenario/FUNDO2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(766, 539));
        setResizable(false);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       new Creditos().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Historia().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Por favor, selecione os itens na sequência,\n da esquerda para a direita e de cima para baixo ");

        new Config().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) throws UnsupportedAudioFileException, IOException, LineUnavailableException {                                       
        /*AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/Música/Tema.wav"));
        Sound.loop();*/
       
        InputStream file = getClass().getResourceAsStream("/Musica/Tema.wav");
        InputStream bufferedIn = new BufferedInputStream(file);
        AudioInputStream audioStream = AudioSystem.getAudioInputStream(bufferedIn);
        Clip clip = AudioSystem.getClip();
        clip.open(audioStream);
        clip.loop(10);
    }      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }
    //métodos para outras classes interagirem com elementos do jogo e com a janela principal    
    public static Avatar getAvatar1() {
        return Jogo.avatar1;
    }

    public static Avatar getAvatar2() {
        return Jogo.avatar2;
    }

    public static JFrame getJanelaJogo() {
        return Jogo.janela1.getFrame();
    }
    public static JanelaJogo getJanela(){
        return Jogo.janela1;
    }

    public static int getUltimoAJogar() {
        return Jogo.ultimoAJogar;
    }

    public static void setUltimoAJogar(int jogador) {
        ultimoAJogar = jogador;
    }

    public static void JanelaSetStatus1(String status) {
        Jogo.janela1.setStatus1(status);
    }

    public static void JanelaSetStatus2(String status) {
        Jogo.janela1.setStatus2(status);
    }

    public static void JanelaRodadas(String status) {
        Jogo.janela1.setRodadas(status);
    }

    public static void JanelaSetCorStatus1() {
        Jogo.janela1.setCorStatus1();
    }

    public static void JanelaSetCorStatus2() {
        Jogo.janela1.setCorStatus2();
    }

    public static float getTotalDeRodadas() {
        return Jogo.totalDeRodadas;
    }

    public static void setTotalDeRodadas(float rodadas) {
        Jogo.totalDeRodadas = rodadas;
    }

    public static BotaoM janelaGetBotaoM(int x, int y) {
        return Jogo.janela1.getBotaoM(x, y);
    }

    public static void janelaSetarAvatar(BotaoM b, boolean ehAvatar1) {
        Jogo.janela1.setarAvatar(b, ehAvatar1);
    }

    public static void janelaSetarElementos(BotaoM b, int x, int y) {
        Jogo.janela1.setarElementos(b, x, y);
    }
    public static void feharJanela(){
        Jogo.janela1.fecharJanela();
    }
    public static void JanelaSetPontosV1(String status) {
        Jogo.janela1.setPontosV1(status);
    }
      public static void JanelaSetPontosV2(String status) {
        Jogo.janela1.setPontosV2(status);
    }
      
      
    public static boolean posicoesIguais(Avatar avatar1, Avatar avatar2){
        int[] pos1= avatar1.getPosicao();
        int[] pos2= avatar2.getPosicao();
        if((pos1[0]==pos2[0])&&(pos1[1]==pos2[1])){
            return true;
        }
        return false;
    }
    //método cri instancia todos os elementos quando o botao de start é clicado
     public static void instanciar() {
        floresta = new Floresta();
        frutas = new MatrizFrutas();
        avatar1 = new Avatar(1);
        avatar2 = new Avatar(2);
        if(Jogo.posicoesIguais(avatar1, avatar2)==true){
            avatar2.outraposicao();
        }
        Floresta.imprime();
        janela1 = new JanelaJogo();
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
